version: '3'

services:
  web:
    build: ./web
    volumes:
      - ./web:/enthu-chat/web
    ports:
      - 3000:3000
  server:
    build: ./server
    volumes:
      - ./server:/enthu-chat/server
    ports:
      - 5000:5000